import mongoose from "mongoose";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(__dirname, "../.env.local") });

const MONGODB_URI = process.env.MONGODB_URI!;

const ToolSchema = new mongoose.Schema({
  name: String, slug: String, tagline: String, category: String,
  pricingModel: String, rating: Number, reviewCount: Number,
  websiteUrl: String, logoUrl: String, features: [String],
  platform: [String], dateAdded: String, isTrending: Boolean,
  isNewTool: Boolean, icon: String,
}, { timestamps: true });

const Tool = mongoose.models.Tool ?? mongoose.model("Tool", ToolSchema);

const TOOLS = [
  { name:"ChatGPT",          slug:"chatgpt",          tagline:"The world's most popular AI assistant for writing, coding, and more.",       category:"text-writing",    pricingModel:"Freemium", rating:4.8, reviewCount:12400, websiteUrl:"https://chatgpt.com",                    logoUrl:"https://cdn.oaistatic.com/_next/static/media/apple-touch-icon.59f2e898.png", features:["Chat interface","Code generation"],     platform:["Web","Mobile"],    dateAdded:"2024-11-01", isTrending:true,  isNewTool:false, icon:"🤖" },
  { name:"Midjourney",       slug:"midjourney",       tagline:"Generate stunning images from text prompts with unmatched quality.",          category:"image-generation", pricingModel:"Paid",     rating:4.7, reviewCount:9800,  websiteUrl:"https://midjourney.com",                 logoUrl:"https://www.midjourney.com/apple-touch-icon.png",                             features:["Text to image","Style control"],        platform:["Web"],             dateAdded:"2024-10-15", isTrending:true,  isNewTool:false, icon:"🎨" },
  { name:"GitHub Copilot",   slug:"github-copilot",   tagline:"AI pair programmer that suggests code completions in real time.",             category:"code-dev",         pricingModel:"Freemium", rating:4.6, reviewCount:8200,  websiteUrl:"https://github.com/features/copilot",   logoUrl:"https://github.githubassets.com/assets/apple-touch-icon-144x144-b882e354c005.png", features:["Code completion","Multi-language"], platform:["Desktop","API"],   dateAdded:"2024-09-20", isTrending:true,  isNewTool:false, icon:"⚡" },
  { name:"ElevenLabs",       slug:"elevenlabs",       tagline:"Ultra-realistic AI voice synthesis and text-to-speech platform.",             category:"audio-music",      pricingModel:"Freemium", rating:4.5, reviewCount:5600,  websiteUrl:"https://elevenlabs.io",                  logoUrl:"https://elevenlabs.io/favicon.ico",                                           features:["Voice cloning","TTS"],                  platform:["Web","API"],       dateAdded:"2024-10-01", isTrending:true,  isNewTool:false, icon:"🎙️" },
  { name:"Perplexity AI",    slug:"perplexity",       tagline:"AI-powered search engine that answers questions with cited sources.",         category:"research",         pricingModel:"Freemium", rating:4.6, reviewCount:6300,  websiteUrl:"https://perplexity.ai",                  logoUrl:"https://www.perplexity.ai/favicon.svg",                                       features:["Cited answers","Real-time search"],     platform:["Web","Mobile"],    dateAdded:"2024-09-05", isTrending:true,  isNewTool:false, icon:"🔬" },
  { name:"Runway Gen-3",     slug:"runway-gen3",      tagline:"Next-gen AI video generation with precise motion control.",                   category:"video-generation", pricingModel:"Paid",     rating:4.4, reviewCount:1900,  websiteUrl:"https://runwayml.com",                   logoUrl:"https://app.runwayml.com/favicon.ico",                                        features:["Video generation","Motion brush"],      platform:["Web"],             dateAdded:"2025-01-12", isTrending:true,  isNewTool:false, icon:"🎬" },
  { name:"Claude 3",         slug:"claude-3",         tagline:"Anthropic's frontier model excelling at analysis and long context.",          category:"text-writing",     pricingModel:"Freemium", rating:4.7, reviewCount:3400,  websiteUrl:"https://claude.ai",                      logoUrl:"https://claude.ai/images/claude_app_icon.png",                                features:["200k context","Document analysis"],     platform:["Web","API"],       dateAdded:"2025-01-05", isTrending:true,  isNewTool:true,  icon:"🧠" },
  { name:"Cursor",           slug:"cursor",           tagline:"AI-first code editor that writes, edits, and debugs code for you.",           category:"code-dev",         pricingModel:"Freemium", rating:4.7, reviewCount:5400,  websiteUrl:"https://cursor.com",                     logoUrl:"https://cursor.com/favicon.ico",                                              features:["Codebase chat","Auto-edit"],            platform:["Desktop"],         dateAdded:"2024-08-01", isTrending:true,  isNewTool:false, icon:"💻" },
  { name:"Notion AI",        slug:"notion-ai",        tagline:"AI built into your workspace — write, summarise, and brainstorm faster.",     category:"productivity",     pricingModel:"Freemium", rating:4.5, reviewCount:7200,  websiteUrl:"https://notion.so/ai",                   logoUrl:"https://www.notion.so/images/favicon.ico",                                    features:["Summarise","Auto-fill"],                platform:["Web","Mobile"],    dateAdded:"2024-08-10", isTrending:true,  isNewTool:false, icon:"📝" },
  { name:"Grammarly",        slug:"grammarly",        tagline:"AI writing assistant that checks grammar, tone, and clarity in real time.",   category:"text-writing",     pricingModel:"Freemium", rating:4.6, reviewCount:15000, websiteUrl:"https://grammarly.com",                  logoUrl:"https://grammarly.com/favicon.ico",                                           features:["Grammar check","Tone detector"],        platform:["Web","Desktop"],   dateAdded:"2024-01-01", isTrending:true,  isNewTool:false, icon:"✍️" },
  { name:"Sora",             slug:"sora",             tagline:"OpenAI's text-to-video model that creates realistic video clips.",            category:"video-generation", pricingModel:"Paid",     rating:4.3, reviewCount:1200,  websiteUrl:"https://openai.com/sora",                logoUrl:"https://cdn.oaistatic.com/_next/static/media/apple-touch-icon.59f2e898.png",  features:["Text to video","HD output"],            platform:["Web"],             dateAdded:"2025-01-10", isTrending:false, isNewTool:true,  icon:"🎥" },
  { name:"Gemini Ultra",     slug:"gemini-ultra",     tagline:"Google's most capable multimodal AI model for complex tasks.",                category:"text-writing",     pricingModel:"Freemium", rating:4.5, reviewCount:2800,  websiteUrl:"https://gemini.google.com",              logoUrl:"https://www.gstatic.com/lamda/images/gemini_sparkle_v002_d4735304ff6292a690345.svg", features:["Multimodal","Code execution"], platform:["Web","Mobile"],    dateAdded:"2025-01-08", isTrending:false, isNewTool:true,  icon:"💎" },
  { name:"Devin",            slug:"devin",            tagline:"The first fully autonomous AI software engineer by Cognition.",               category:"code-dev",         pricingModel:"Paid",     rating:4.2, reviewCount:980,   websiteUrl:"https://devin.ai",                       logoUrl:"https://preview.devin.ai/favicon.ico",                                        features:["Autonomous coding","Bug fixing"],       platform:["Web"],             dateAdded:"2025-01-15", isTrending:false, isNewTool:true,  icon:"🤖" },
  { name:"Udio",             slug:"udio",             tagline:"Create full songs with vocals and instruments from a text prompt.",           category:"audio-music",      pricingModel:"Free",     rating:4.3, reviewCount:1500,  websiteUrl:"https://udio.com",                       logoUrl:"https://www.udio.com/favicon.ico",                                            features:["Music generation","Lyrics"],            platform:["Web"],             dateAdded:"2025-01-03", isTrending:false, isNewTool:true,  icon:"🎸" },
  { name:"Jasper AI",        slug:"jasper-ai",        tagline:"AI copywriting platform built for marketing teams and content creators.",    category:"text-writing",     pricingModel:"Paid",     rating:4.2, reviewCount:4500,  websiteUrl:"https://jasper.ai",                      logoUrl:"",                                                                            features:["Brand voice","Templates"],              platform:["Web"],             dateAdded:"2024-05-10", isTrending:false, isNewTool:false, icon:"✍️" },
  { name:"Copy.ai",          slug:"copy-ai",          tagline:"Generate marketing copy, blog posts, and social content in seconds.",        category:"text-writing",     pricingModel:"Freemium", rating:4.1, reviewCount:3800,  websiteUrl:"https://copy.ai",                        logoUrl:"",                                                                            features:["90+ templates","Bulk generation"],      platform:["Web"],             dateAdded:"2024-04-20", isTrending:false, isNewTool:false, icon:"📋" },
  { name:"Stable Diffusion", slug:"stable-diffusion", tagline:"Open-source image generation model with endless customisation.",             category:"image-generation", pricingModel:"Free",     rating:4.3, reviewCount:11200, websiteUrl:"https://stability.ai",                   logoUrl:"",                                                                            features:["Open source","LoRA support"],           platform:["Desktop","API"],   dateAdded:"2024-06-01", isTrending:false, isNewTool:false, icon:"🖼️" },
  { name:"DALL-E 3",         slug:"dalle-3",          tagline:"OpenAI's image generation model with precise prompt following.",              category:"image-generation", pricingModel:"Freemium", rating:4.5, reviewCount:7800,  websiteUrl:"https://openai.com/dall-e-3",            logoUrl:"https://cdn.oaistatic.com/_next/static/media/apple-touch-icon.59f2e898.png",  features:["Text to image","Inpainting"],           platform:["Web","API"],       dateAdded:"2024-07-01", isTrending:false, isNewTool:false, icon:"🎨" },
  { name:"Suno AI",          slug:"suno-ai",          tagline:"Generate complete songs with lyrics and music from a simple text prompt.",   category:"audio-music",      pricingModel:"Freemium", rating:4.5, reviewCount:4200,  websiteUrl:"https://suno.com",                       logoUrl:"",                                                                            features:["Full song gen","Custom style"],         platform:["Web"],             dateAdded:"2024-09-10", isTrending:false, isNewTool:false, icon:"🎵" },
  { name:"Quillbot",         slug:"quillbot",         tagline:"AI paraphrasing and summarisation tool trusted by millions of students.",     category:"text-writing",     pricingModel:"Freemium", rating:4.3, reviewCount:9200,  websiteUrl:"https://quillbot.com",                   logoUrl:"",                                                                            features:["Paraphrase","Summariser"],              platform:["Web","Desktop"],   dateAdded:"2024-02-10", isTrending:false, isNewTool:false, icon:"📝" },
];

async function seed() {
  await mongoose.connect(MONGODB_URI);
  console.log("Connected to MongoDB");

  await Tool.deleteMany({});
  console.log("Cleared existing tools");

  await Tool.insertMany(TOOLS);
  console.log(`Seeded ${TOOLS.length} tools`);

  await mongoose.disconnect();
  console.log("Done!");
}

seed().catch(console.error);
