import type { Tool } from "@/components/aigrid/ToolCard";

// Extended Tool type with features + platform for search page
export interface SearchTool extends Tool {
  features: string[];
  platform: string[];
  dateAdded: string; // ISO date string
  websiteUrl: string;
}

export const MOCK_TOOLS: SearchTool[] = [
  { id:"1",  name:"ChatGPT",         slug:"chatgpt",          tagline:"The world's most popular AI assistant for writing, coding, and more.",      category:"text-writing",   pricingModel:"Freemium", rating:4.8, reviewCount:12400, features:["Chat interface","Code generation"],        platform:["Web","Mobile"],   dateAdded:"2024-11-01", logoUrl:"https://cdn.oaistatic.com/_next/static/media/apple-touch-icon.59f2e898.png", websiteUrl: "https://chatgpt.com" },
  { id:"2",  name:"Midjourney",      slug:"midjourney",       tagline:"Generate stunning images from text prompts with unmatched quality.",         category:"image-generation",    pricingModel:"Paid",     rating:4.7, reviewCount:9800,  features:["Text to image","Style control"],           platform:["Web"],            dateAdded:"2024-10-15", logoUrl:"https://www.midjourney.com/apple-touch-icon.png", websiteUrl: "https://midjourney.com" },
  { id:"3",  name:"GitHub Copilot",  slug:"github-copilot",   tagline:"AI pair programmer that suggests code completions in real time.",            category:"code-dev",       pricingModel:"Freemium", rating:4.6, reviewCount:8200,  features:["Code completion","Multi-language"],        platform:["Desktop","API"],  dateAdded:"2024-09-20", logoUrl:"https://github.githubassets.com/assets/apple-touch-icon-144x144-b882e354c005.png", websiteUrl: "https://github.com/features/copilot" },
  { id:"4",  name:"ElevenLabs",      slug:"elevenlabs",       tagline:"Ultra-realistic AI voice synthesis and text-to-speech platform.",            category:"audio-music",    pricingModel:"Freemium", rating:4.5, reviewCount:5600,  features:["Voice cloning","TTS"],                     platform:["Web","API"],      dateAdded:"2024-10-01", logoUrl:"https://elevenlabs.io/favicon.ico", websiteUrl: "https://elevenlabs.io" },
  { id:"5",  name:"Notion AI",       slug:"notion-ai",        tagline:"AI writing and summarisation built right into your Notion workspace.",       category:"productivity",   pricingModel:"Freemium", rating:4.4, reviewCount:7100,  features:["Summarise","Auto-fill"],                   platform:["Web","Mobile"],   dateAdded:"2024-08-10", logoUrl:"https://www.notion.so/images/favicon.ico", websiteUrl: "https://notion.so/ai" },
  { id:"6",  name:"Perplexity",      slug:"perplexity",       tagline:"AI-powered search engine that answers questions with cited sources.",        category:"research",       pricingModel:"Freemium", rating:4.6, reviewCount:6300,  features:["Cited answers","Real-time search"],        platform:["Web","Mobile"],   dateAdded:"2024-09-05", logoUrl:"https://www.perplexity.ai/favicon.svg", websiteUrl: "https://perplexity.ai" },
  { id:"7",  name:"Sora",            slug:"sora",             tagline:"OpenAI's text-to-video model that creates realistic video clips.",           category:"video-generation",    pricingModel:"Paid",     rating:4.3, reviewCount:1200,  features:["Text to video","HD output"],               platform:["Web"],            dateAdded:"2025-01-10", logoUrl:"https://cdn.oaistatic.com/_next/static/media/apple-touch-icon.59f2e898.png", websiteUrl: "https://openai.com/sora" },
  { id:"8",  name:"Claude 3",        slug:"claude-3",         tagline:"Anthropic's frontier model excelling at analysis and long context.",         category:"text-writing",   pricingModel:"Freemium", rating:4.7, reviewCount:3400,  features:["200k context","Document analysis"],        platform:["Web","API"],      dateAdded:"2025-01-05", logoUrl:"https://claude.ai/images/claude_app_icon.png", websiteUrl: "https://claude.ai" },
  { id:"9",  name:"Gemini Ultra",    slug:"gemini-ultra",     tagline:"Google's most capable multimodal AI model for complex tasks.",               category:"text-writing",   pricingModel:"Freemium", rating:4.5, reviewCount:2800,  features:["Multimodal","Code execution"],             platform:["Web","Mobile"],   dateAdded:"2025-01-08", logoUrl:"https://www.gstatic.com/lamda/images/gemini_sparkle_v002_d4735304ff6292a690345.svg", websiteUrl: "https://gemini.google.com" },
  { id:"10", name:"Runway Gen-3",    slug:"runway-gen3",      tagline:"Next-gen AI video generation with precise motion control.",                  category:"video-generation",    pricingModel:"Paid",     rating:4.4, reviewCount:1900,  features:["Video generation","Motion brush"],         platform:["Web"],            dateAdded:"2025-01-12", logoUrl:"https://app.runwayml.com/favicon.ico", websiteUrl: "https://runwayml.com" },
  { id:"11", name:"Devin",           slug:"devin",            tagline:"The first fully autonomous AI software engineer by Cognition.",              category:"code-dev",       pricingModel:"Paid",     rating:4.2, reviewCount:980,   features:["Autonomous coding","Bug fixing"],          platform:["Web"],            dateAdded:"2025-01-15", logoUrl:"https://preview.devin.ai/favicon.ico", websiteUrl: "https://devin.ai" },
  { id:"12", name:"Udio",            slug:"udio",             tagline:"Create full songs with vocals and instruments from a text prompt.",          category:"audio-music",    pricingModel:"Free",     rating:4.3, reviewCount:1500,  features:["Music generation","Lyrics"],               platform:["Web"],            dateAdded:"2025-01-03", logoUrl:"https://www.udio.com/favicon.ico", websiteUrl: "https://udio.com" },
  { id:"13", name:"Grok 2",          slug:"grok-2",           tagline:"xAI's real-time AI assistant with live internet access.",                    category:"research",       pricingModel:"Freemium", rating:4.1, reviewCount:2100,  features:["Real-time data","Image understanding"],   platform:["Web","Mobile"],   dateAdded:"2024-12-20", logoUrl:"https://grok.x.ai/favicon.ico", websiteUrl: "https://x.ai" },
  { id:"14", name:"Bolt.new",        slug:"bolt-new",         tagline:"Full-stack web app builder powered by AI — deploy in seconds.",             category:"code-dev",       pricingModel:"Freemium", rating:4.5, reviewCount:3200,  features:["Full-stack gen","One-click deploy"],       platform:["Web"],            dateAdded:"2024-12-15", logoUrl:"https://bolt.new/favicon.ico", websiteUrl: "https://bolt.new" },
  { id:"15", name:"DALL-E 3",        slug:"dalle-3",          tagline:"OpenAI's image generation model with precise prompt following.",             category:"image-generation",    pricingModel:"Freemium", rating:4.5, reviewCount:7800,  features:["Text to image","Inpainting"],              platform:["Web","API"],      dateAdded:"2024-07-01", logoUrl:"https://cdn.oaistatic.com/_next/static/media/apple-touch-icon.59f2e898.png", websiteUrl: "https://openai.com/dall-e-3" },
  { id:"16", name:"Stable Diffusion",slug:"stable-diffusion", tagline:"Open-source image generation model with endless customisation.",            category:"image-generation",    pricingModel:"Free",     rating:4.3, reviewCount:11200, features:["Open source","LoRA support"],              platform:["Desktop","API"],  dateAdded:"2024-06-01", logoUrl:"", websiteUrl: "https://stability.ai" },
  { id:"17", name:"Jasper AI",       slug:"jasper-ai",        tagline:"AI copywriting platform built for marketing teams and content creators.",   category:"text-writing",   pricingModel:"Paid",     rating:4.2, reviewCount:4500,  features:["Brand voice","Templates"],                 platform:["Web"],            dateAdded:"2024-05-10", logoUrl:"", websiteUrl: "https://jasper.ai" },
  { id:"18", name:"Copy.ai",         slug:"copy-ai",          tagline:"Generate marketing copy, blog posts, and social content in seconds.",       category:"text-writing",   pricingModel:"Freemium", rating:4.1, reviewCount:3800,  features:["90+ templates","Bulk generation"],         platform:["Web"],            dateAdded:"2024-04-20", logoUrl:"", websiteUrl: "https://copy.ai" },
  { id:"19", name:"Writesonic",      slug:"writesonic",        tagline:"AI writer that creates SEO-optimised articles and landing pages.",          category:"text-writing",   pricingModel:"Freemium", rating:4.0, reviewCount:3200,  features:["SEO mode","Factual articles"],             platform:["Web","API"],      dateAdded:"2024-04-15", logoUrl:"", websiteUrl: "https://writesonic.com" },
  { id:"20", name:"Murf AI",         slug:"murf-ai",          tagline:"Studio-quality AI voiceovers for videos, podcasts, and presentations.",     category:"audio-music",    pricingModel:"Freemium", rating:4.4, reviewCount:2900,  features:["120+ voices","Pitch control"],             platform:["Web"],            dateAdded:"2024-05-01", logoUrl:"", websiteUrl: "https://murf.ai" },
  { id:"21", name:"Descript",        slug:"descript",         tagline:"Edit audio and video by editing text — the future of media production.",    category:"audio-music",    pricingModel:"Freemium", rating:4.5, reviewCount:4100,  features:["Overdub","Screen recording"],              platform:["Desktop","Web"],  dateAdded:"2024-03-10", logoUrl:"", websiteUrl: "https://descript.com" },
  { id:"22", name:"Synthesia",       slug:"synthesia",        tagline:"Create professional AI videos with avatars — no camera needed.",            category:"video-generation",    pricingModel:"Paid",     rating:4.3, reviewCount:3600,  features:["AI avatars","140 languages"],              platform:["Web"],            dateAdded:"2024-06-15", logoUrl:"", websiteUrl: "https://synthesia.io" },
  { id:"23", name:"HeyGen",          slug:"heygen",           tagline:"AI video generator with realistic talking avatars for any use case.",       category:"video-generation",    pricingModel:"Freemium", rating:4.4, reviewCount:2700,  features:["Avatar cloning","Video translation"],     platform:["Web"],            dateAdded:"2024-07-20", logoUrl:"", websiteUrl: "https://heygen.com" },
  { id:"24", name:"Cursor",          slug:"cursor",           tagline:"The AI-first code editor built for pair programming with GPT-4.",           category:"code-dev",       pricingModel:"Freemium", rating:4.7, reviewCount:5400,  features:["Codebase chat","Auto-edit"],               platform:["Desktop"],        dateAdded:"2024-08-01", logoUrl:"", websiteUrl: "https://cursor.com" },
  { id:"25", name:"Tabnine",         slug:"tabnine",          tagline:"AI code completion that learns your codebase and coding style.",            category:"code-dev",       pricingModel:"Freemium", rating:4.2, reviewCount:4800,  features:["Private model","IDE plugins"],             platform:["Desktop","API"],  dateAdded:"2024-03-01", logoUrl:"", websiteUrl: "https://tabnine.com" },
  { id:"26", name:"Codeium",         slug:"codeium",          tagline:"Free AI coding assistant with support for 70+ programming languages.",      category:"code-dev",       pricingModel:"Free",     rating:4.3, reviewCount:3900,  features:["70+ languages","Chat mode"],               platform:["Desktop","Web"],  dateAdded:"2024-04-01", logoUrl:"", websiteUrl: "https://codeium.com" },
  { id:"27", name:"Otter.ai",        slug:"otter-ai",         tagline:"AI meeting assistant that records, transcribes, and summarises calls.",     category:"productivity",   pricingModel:"Freemium", rating:4.3, reviewCount:6200,  features:["Live transcription","Action items"],       platform:["Web","Mobile"],   dateAdded:"2024-02-15", logoUrl:"", websiteUrl: "https://otter.ai" },
  { id:"28", name:"Fireflies.ai",    slug:"fireflies-ai",     tagline:"AI notetaker that joins your meetings and creates searchable transcripts.", category:"productivity",   pricingModel:"Freemium", rating:4.2, reviewCount:4700,  features:["CRM sync","Topic tracker"],                platform:["Web"],            dateAdded:"2024-03-20", logoUrl:"", websiteUrl: "https://fireflies.ai" },
  { id:"29", name:"Motion",          slug:"motion",           tagline:"AI calendar that automatically schedules your tasks and meetings.",         category:"productivity",   pricingModel:"Paid",     rating:4.4, reviewCount:3100,  features:["Auto-schedule","Priority AI"],             platform:["Web","Mobile"],   dateAdded:"2024-05-15", logoUrl:"", websiteUrl: "https://usemotion.com" },
  { id:"30", name:"Reclaim.ai",      slug:"reclaim-ai",       tagline:"Smart scheduling assistant that protects time for your most important work.",category:"productivity",  pricingModel:"Freemium", rating:4.3, reviewCount:2800,  features:["Habit scheduling","Slack sync"],           platform:["Web"],            dateAdded:"2024-04-10", logoUrl:"", websiteUrl: "https://reclaim.ai" },
  { id:"31", name:"Elicit",          slug:"elicit",           tagline:"AI research assistant that finds and summarises academic papers for you.",  category:"research",       pricingModel:"Freemium", rating:4.4, reviewCount:2200,  features:["Paper search","Data extraction"],          platform:["Web"],            dateAdded:"2024-06-01", logoUrl:"", websiteUrl: "https://elicit.org" },
  { id:"32", name:"Consensus",       slug:"consensus",        tagline:"Search engine that extracts findings directly from scientific research.",   category:"research",       pricingModel:"Freemium", rating:4.3, reviewCount:1900,  features:["Evidence synthesis","Citation export"],   platform:["Web"],            dateAdded:"2024-05-20", logoUrl:"", websiteUrl: "https://consensus.app" },
  { id:"33", name:"Semantic Scholar",slug:"semantic-scholar", tagline:"Free AI-powered research tool for exploring 200M+ academic papers.",       category:"research",       pricingModel:"Free",     rating:4.2, reviewCount:3400,  features:["Citation graph","TL;DR summaries"],        platform:["Web","API"],      dateAdded:"2024-01-10", logoUrl:"", websiteUrl: "https://semanticscholar.org" },
  { id:"34", name:"Adobe Firefly",   slug:"adobe-firefly",    tagline:"Generative AI built into Adobe Creative Cloud for designers.",             category:"image-generation",    pricingModel:"Freemium", rating:4.4, reviewCount:5100,  features:["Generative fill","Text effects"],          platform:["Web","Desktop"],  dateAdded:"2024-07-10", logoUrl:"", websiteUrl: "https://adobe.com/firefly" },
  { id:"35", name:"Canva AI",        slug:"canva-ai",         tagline:"AI design tools built into Canva — generate images, text, and layouts.",   category:"image-generation",    pricingModel:"Freemium", rating:4.5, reviewCount:8900,  features:["Magic design","Background remover"],      platform:["Web","Mobile"],   dateAdded:"2024-06-20", logoUrl:"", websiteUrl: "https://canva.com" },
  { id:"36", name:"Luma AI",         slug:"luma-ai",          tagline:"Create photorealistic 3D captures and AI video from text or images.",      category:"video-generation",    pricingModel:"Freemium", rating:4.3, reviewCount:1600,  features:["3D capture","Dream Machine"],              platform:["Web","Mobile"],   dateAdded:"2024-09-01", logoUrl:"", websiteUrl: "https://lumalabs.ai" },
  { id:"37", name:"Pika Labs",       slug:"pika-labs",        tagline:"AI video generation tool that brings your ideas to life in seconds.",      category:"video-generation",    pricingModel:"Freemium", rating:4.2, reviewCount:2300,  features:["Text to video","Modify region"],           platform:["Web"],            dateAdded:"2024-08-15", logoUrl:"", websiteUrl: "https://pika.art" },
  { id:"38", name:"Suno AI",         slug:"suno-ai",          tagline:"Generate complete songs with lyrics and music from a simple text prompt.", category:"audio-music",    pricingModel:"Freemium", rating:4.5, reviewCount:4200,  features:["Full song gen","Custom style"],            platform:["Web"],            dateAdded:"2024-09-10", logoUrl:"", websiteUrl: "https://suno.com" },
  { id:"39", name:"Adobe Podcast",   slug:"adobe-podcast",    tagline:"AI audio tools that enhance speech and remove background noise instantly.",category:"audio-music",    pricingModel:"Free",     rating:4.4, reviewCount:3100,  features:["Enhance speech","Mic check"],              platform:["Web"],            dateAdded:"2024-07-05", logoUrl:"", websiteUrl: "https://podcast.adobe.com" },
  { id:"40", name:"Krisp",           slug:"krisp",            tagline:"AI noise cancellation app that removes background noise from any call.",   category:"audio-music",    pricingModel:"Freemium", rating:4.3, reviewCount:5600,  features:["Noise removal","Echo cancel"],             platform:["Desktop","Mobile"],dateAdded:"2024-02-01", logoUrl:"", websiteUrl: "https://krisp.ai" },
  { id:"41", name:"Replit AI",       slug:"replit-ai",        tagline:"AI coding assistant built into Replit's online IDE for all skill levels.", category:"code-dev",       pricingModel:"Freemium", rating:4.1, reviewCount:4300,  features:["Ghostwriter","Explain code"],              platform:["Web"],            dateAdded:"2024-05-01", logoUrl:"", websiteUrl: "https://replit.com/ai" },
  { id:"42", name:"v0 by Vercel",    slug:"v0-vercel",        tagline:"Generate React UI components from text descriptions using shadcn/ui.",     category:"code-dev",       pricingModel:"Freemium", rating:4.6, reviewCount:2800,  features:["React gen","shadcn/ui"],                   platform:["Web"],            dateAdded:"2024-10-01", logoUrl:"", websiteUrl: "https://v0.dev" },
  { id:"43", name:"Lovable",         slug:"lovable",          tagline:"Build full-stack web apps from a prompt — no coding experience needed.",   category:"code-dev",       pricingModel:"Freemium", rating:4.4, reviewCount:1900,  features:["Full-stack","GitHub sync"],                platform:["Web"],            dateAdded:"2024-11-15", logoUrl:"", websiteUrl: "https://lovable.dev" },
  { id:"44", name:"Wordtune",        slug:"wordtune",         tagline:"AI writing companion that rewrites, shortens, and expands your sentences.", category:"text-writing",   pricingModel:"Freemium", rating:4.2, reviewCount:4100,  features:["Rewrite","Spices"],                        platform:["Web","Mobile"],   dateAdded:"2024-03-15", logoUrl:"", websiteUrl: "https://wordtune.com" },
  { id:"45", name:"Grammarly",       slug:"grammarly",        tagline:"AI writing assistant that checks grammar, tone, and clarity in real time.", category:"text-writing",   pricingModel:"Freemium", rating:4.6, reviewCount:18000, features:["Grammar check","Tone detector"],           platform:["Web","Desktop","Mobile"],dateAdded:"2024-01-01",logoUrl:"", websiteUrl: "https://grammarly.com" },
  { id:"46", name:"Quillbot",        slug:"quillbot",         tagline:"AI paraphrasing and summarisation tool trusted by millions of students.",  category:"text-writing",   pricingModel:"Freemium", rating:4.3, reviewCount:9200,  features:["Paraphrase","Summariser"],                 platform:["Web","Desktop"],  dateAdded:"2024-02-10", logoUrl:"", websiteUrl: "https://quillbot.com" },
  { id:"47", name:"Taskade",         slug:"taskade",          tagline:"AI-powered project management and collaboration workspace for teams.",     category:"productivity",   pricingModel:"Freemium", rating:4.2, reviewCount:2600,  features:["AI agents","Mind maps"],                   platform:["Web","Mobile","Desktop"],dateAdded:"2024-06-10",logoUrl:"", websiteUrl: "https://taskade.com" },
  { id:"48", name:"Mem.ai",          slug:"mem-ai",           tagline:"Self-organising AI workspace that surfaces the right notes at the right time.",category:"productivity",pricingModel:"Freemium", rating:4.1, reviewCount:1800,  features:["Auto-organise","Smart search"],            platform:["Web","Mobile"],   dateAdded:"2024-07-15", logoUrl:"", websiteUrl: "https://mem.ai" },
  { id:"49", name:"Consensus AI",    slug:"consensus-ai",     tagline:"Find scientific consensus on any topic using AI-powered paper analysis.",  category:"research",       pricingModel:"Freemium", rating:4.2, reviewCount:1400,  features:["Consensus meter","GPT-4 summaries"],      platform:["Web"],            dateAdded:"2024-08-20", logoUrl:"", websiteUrl: "https://consensus.app" },
  { id:"50", name:"Scite.ai",        slug:"scite-ai",         tagline:"Discover how research has been cited — supporting or contrasting evidence.",category:"research",       pricingModel:"Paid",     rating:4.3, reviewCount:1700,  features:["Citation context","Reference check"],     platform:["Web","API"],      dateAdded:"2024-09-15", logoUrl:"", websiteUrl: "https://scite.ai" },
];
