import { subHours, subDays } from "date-fns";
import type { SearchTool } from "./mock-tools";

// Generate 40 tools spread across the past 14 days
export const NEW_TOOLS_FEED: SearchTool[] = [
  // Today (last 24 hours)
  { id:"n1",  name:"Krea AI",         slug:"krea-ai",         tagline:"Real-time AI image generation with instant previews as you type.",           category:"image-video",    pricingModel:"Freemium", rating:4.6, reviewCount:340,   features:["Real-time gen","Style mixing"],      platform:["Web"],           dateAdded:subHours(new Date(), 3).toISOString(),  logoUrl:"", websiteUrl:"https://krea.ai" },
  { id:"n2",  name:"Pieces",          slug:"pieces",          tagline:"AI-powered code snippet manager with context-aware search.",                category:"code-dev",       pricingModel:"Free",     rating:4.5, reviewCount:280,   features:["Code snippets","AI search"],         platform:["Desktop","Web"], dateAdded:subHours(new Date(), 8).toISOString(),  logoUrl:"", websiteUrl:"https://pieces.app" },
  { id:"n3",  name:"Voicemod AI",     slug:"voicemod-ai",     tagline:"Real-time AI voice changer for gaming and content creation.",               category:"audio-music",    pricingModel:"Freemium", rating:4.3, reviewCount:520,   features:["Voice effects","Real-time"],         platform:["Desktop"],       dateAdded:subHours(new Date(), 12).toISOString(), logoUrl:"", websiteUrl:"https://voicemod.net" },
  
  // Yesterday
  { id:"n4",  name:"Gamma",           slug:"gamma",           tagline:"Create beautiful presentations and documents with AI in seconds.",          category:"productivity",   pricingModel:"Freemium", rating:4.7, reviewCount:890,   features:["Auto-design","Templates"],           platform:["Web"],           dateAdded:subDays(new Date(), 1).toISOString(),   logoUrl:"", websiteUrl:"https://gamma.app" },
  { id:"n5",  name:"Ideogram",        slug:"ideogram",        tagline:"AI image generator that excels at rendering text within images.",           category:"image-video",    pricingModel:"Freemium", rating:4.4, reviewCount:670,   features:["Text rendering","High quality"],     platform:["Web"],           dateAdded:subDays(new Date(), 1).toISOString(),   logoUrl:"", websiteUrl:"https://ideogram.ai" },
  { id:"n6",  name:"Phind",           slug:"phind",           tagline:"AI search engine optimized for developers and technical questions.",        category:"research",       pricingModel:"Free",     rating:4.5, reviewCount:1200,  features:["Code search","Technical Q&A"],      platform:["Web"],           dateAdded:subDays(new Date(), 1).toISOString(),   logoUrl:"", websiteUrl:"https://phind.com" },
  
  // 2 days ago
  { id:"n7",  name:"Rewind AI",       slug:"rewind-ai",       tagline:"Search your life with AI — records everything you see and hear.",          category:"productivity",   pricingModel:"Paid",     rating:4.2, reviewCount:450,   features:["Screen recording","AI search"],      platform:["Desktop"],       dateAdded:subDays(new Date(), 2).toISOString(),   logoUrl:"", websiteUrl:"https://rewind.ai" },
  { id:"n8",  name:"Fal.ai",          slug:"fal-ai",          tagline:"Lightning-fast AI image generation API for developers.",                    category:"image-video",    pricingModel:"API-only", rating:4.6, reviewCount:320,   features:["Fast inference","API"],              platform:["API"],           dateAdded:subDays(new Date(), 2).toISOString(),   logoUrl:"", websiteUrl:"https://fal.ai" },
  { id:"n9",  name:"Superhuman AI",   slug:"superhuman-ai",   tagline:"AI-powered email client that helps you reach inbox zero faster.",          category:"productivity",   pricingModel:"Paid",     rating:4.8, reviewCount:2100,  features:["Email triage","Auto-reply"],         platform:["Web","Mobile"],  dateAdded:subDays(new Date(), 2).toISOString(),   logoUrl:"", websiteUrl:"https://superhuman.com" },
  { id:"n10", name:"Warp AI",         slug:"warp-ai",         tagline:"Modern terminal with AI command suggestions and natural language search.",  category:"code-dev",       pricingModel:"Free",     rating:4.7, reviewCount:1800,  features:["AI commands","Terminal"],            platform:["Desktop"],       dateAdded:subDays(new Date(), 2).toISOString(),   logoUrl:"", websiteUrl:"https://warp.dev" },
  
  // 3 days ago
  { id:"n11", name:"Loom AI",         slug:"loom-ai",         tagline:"AI-powered video messages with auto-generated titles and summaries.",       category:"productivity",   pricingModel:"Freemium", rating:4.6, reviewCount:3400,  features:["Video messages","AI summaries"],     platform:["Web","Desktop"], dateAdded:subDays(new Date(), 3).toISOString(),   logoUrl:"", websiteUrl:"https://loom.com" },
  { id:"n12", name:"Playground AI",   slug:"playground-ai",   tagline:"Free AI image generator with advanced editing and mixing tools.",           category:"image-video",    pricingModel:"Free",     rating:4.5, reviewCount:2800,  features:["Image editing","Free tier"],         platform:["Web"],           dateAdded:subDays(new Date(), 3).toISOString(),   logoUrl:"", websiteUrl:"https://playground.com" },
  { id:"n13", name:"Cody",            slug:"cody",            tagline:"AI coding assistant that knows your entire codebase.",                      category:"code-dev",       pricingModel:"Freemium", rating:4.4, reviewCount:980,   features:["Codebase context","Chat"],           platform:["Desktop"],       dateAdded:subDays(new Date(), 3).toISOString(),   logoUrl:"", websiteUrl:"https://sourcegraph.com/cody" },
  { id:"n14", name:"Riffusion",       slug:"riffusion",       tagline:"Generate music from text prompts using stable diffusion.",                  category:"audio-music",    pricingModel:"Free",     rating:4.2, reviewCount:1500,  features:["Music gen","Open source"],          platform:["Web"],           dateAdded:subDays(new Date(), 3).toISOString(),   logoUrl:"", websiteUrl:"https://riffusion.com" },
  
  // 4 days ago
  { id:"n15", name:"Mem",             slug:"mem",             tagline:"AI-powered note-taking app that auto-organizes your thoughts.",             category:"productivity",   pricingModel:"Freemium", rating:4.3, reviewCount:670,   features:["Auto-organize","Smart search"],      platform:["Web","Mobile"],  dateAdded:subDays(new Date(), 4).toISOString(),   logoUrl:"", websiteUrl:"https://mem.ai" },
  { id:"n16", name:"Leonardo AI",     slug:"leonardo-ai",     tagline:"Create production-quality visual assets with AI-powered speed.",            category:"image-video",    pricingModel:"Freemium", rating:4.7, reviewCount:4200,  features:["Asset generation","Game art"],       platform:["Web"],           dateAdded:subDays(new Date(), 4).toISOString(),   logoUrl:"", websiteUrl:"https://leonardo.ai" },
  { id:"n17", name:"Sourcegraph Cody",slug:"sourcegraph-cody",tagline:"AI coding assistant with deep codebase understanding.",                     category:"code-dev",       pricingModel:"Freemium", rating:4.5, reviewCount:1200,  features:["Code search","Context-aware"],       platform:["Desktop"],       dateAdded:subDays(new Date(), 4).toISOString(),   logoUrl:"", websiteUrl:"https://sourcegraph.com" },
  
  // 5 days ago
  { id:"n18", name:"Humata AI",       slug:"humata-ai",       tagline:"ChatGPT for your files — ask questions about any document.",                category:"research",       pricingModel:"Freemium", rating:4.4, reviewCount:890,   features:["Document Q&A","Citations"],          platform:["Web"],           dateAdded:subDays(new Date(), 5).toISOString(),   logoUrl:"", websiteUrl:"https://humata.ai" },
  { id:"n19", name:"Clipdrop",        slug:"clipdrop",        tagline:"AI-powered image editing tools for creators and developers.",               category:"image-video",    pricingModel:"Freemium", rating:4.6, reviewCount:3100,  features:["Background removal","Upscale"],      platform:["Web","Mobile"],  dateAdded:subDays(new Date(), 5).toISOString(),   logoUrl:"", websiteUrl:"https://clipdrop.co" },
  { id:"n20", name:"Bearly AI",       slug:"bearly-ai",       tagline:"AI research assistant that lives in your desktop workflow.",                category:"research",       pricingModel:"Freemium", rating:4.3, reviewCount:560,   features:["Desktop app","Quick access"],        platform:["Desktop"],       dateAdded:subDays(new Date(), 5).toISOString(),   logoUrl:"", websiteUrl:"https://bearly.ai" },
  { id:"n21", name:"Soundraw",        slug:"soundraw",        tagline:"Create royalty-free music with AI for videos and podcasts.",                category:"audio-music",    pricingModel:"Paid",     rating:4.4, reviewCount:1800,  features:["Royalty-free","Customizable"],       platform:["Web"],           dateAdded:subDays(new Date(), 5).toISOString(),   logoUrl:"", websiteUrl:"https://soundraw.io" },
  
  // 6 days ago
  { id:"n22", name:"Tome",            slug:"tome",            tagline:"AI-powered storytelling format for presentations and pitches.",             category:"productivity",   pricingModel:"Freemium", rating:4.5, reviewCount:2300,  features:["Story format","Auto-design"],        platform:["Web"],           dateAdded:subDays(new Date(), 6).toISOString(),   logoUrl:"", websiteUrl:"https://tome.app" },
  { id:"n23", name:"Lexica",          slug:"lexica",          tagline:"Search engine and generator for Stable Diffusion images.",                  category:"image-video",    pricingModel:"Freemium", rating:4.3, reviewCount:1900,  features:["Image search","Prompt library"],     platform:["Web"],           dateAdded:subDays(new Date(), 6).toISOString(),   logoUrl:"", websiteUrl:"https://lexica.art" },
  { id:"n24", name:"Mintlify",        slug:"mintlify",        tagline:"AI-powered documentation writer for your codebase.",                        category:"code-dev",       pricingModel:"Freemium", rating:4.6, reviewCount:780,   features:["Auto-docs","Code analysis"],         platform:["Web"],           dateAdded:subDays(new Date(), 6).toISOString(),   logoUrl:"", websiteUrl:"https://mintlify.com" },
  { id:"n25", name:"Consensus",       slug:"consensus",       tagline:"AI search engine that finds answers in research papers.",                   category:"research",       pricingModel:"Freemium", rating:4.7, reviewCount:1400,  features:["Paper search","Evidence"],           platform:["Web"],           dateAdded:subDays(new Date(), 6).toISOString(),   logoUrl:"", websiteUrl:"https://consensus.app" },
  
  // Last week (7-13 days ago)
  { id:"n26", name:"Magical",         slug:"magical",         tagline:"AI text expander that works everywhere you type.",                          category:"productivity",   pricingModel:"Free",     rating:4.5, reviewCount:4500,  features:["Text expansion","Auto-fill"],        platform:["Desktop"],       dateAdded:subDays(new Date(), 7).toISOString(),   logoUrl:"", websiteUrl:"https://magical.so" },
  { id:"n27", name:"Artbreeder",      slug:"artbreeder",      tagline:"Collaborative AI art platform for creating characters and landscapes.",     category:"image-video",    pricingModel:"Freemium", rating:4.2, reviewCount:2700,  features:["Character gen","Mixing"],            platform:["Web"],           dateAdded:subDays(new Date(), 7).toISOString(),   logoUrl:"", websiteUrl:"https://artbreeder.com" },
  { id:"n28", name:"Aider",           slug:"aider",           tagline:"AI pair programming in your terminal with git integration.",                category:"code-dev",       pricingModel:"Free",     rating:4.6, reviewCount:890,   features:["Terminal AI","Git aware"],           platform:["Desktop"],       dateAdded:subDays(new Date(), 8).toISOString(),   logoUrl:"", websiteUrl:"https://aider.chat" },
  { id:"n29", name:"Mubert",          slug:"mubert",          tagline:"AI music generation for content creators and developers.",                  category:"audio-music",    pricingModel:"Freemium", rating:4.3, reviewCount:2100,  features:["Royalty-free","API access"],         platform:["Web","API"],     dateAdded:subDays(new Date(), 8).toISOString(),   logoUrl:"", websiteUrl:"https://mubert.com" },
  { id:"n30", name:"Reflect",         slug:"reflect",         tagline:"AI-powered note-taking with end-to-end encryption.",                        category:"productivity",   pricingModel:"Paid",     rating:4.4, reviewCount:1200,  features:["Encrypted","Backlinks"],             platform:["Web","Mobile"],  dateAdded:subDays(new Date(), 9).toISOString(),   logoUrl:"", websiteUrl:"https://reflect.app" },
  { id:"n31", name:"Picsart AI",      slug:"picsart-ai",      tagline:"AI photo editor with one-tap enhancements and effects.",                    category:"image-video",    pricingModel:"Freemium", rating:4.5, reviewCount:8900,  features:["Photo editing","Effects"],           platform:["Web","Mobile"],  dateAdded:subDays(new Date(), 9).toISOString(),   logoUrl:"", websiteUrl:"https://picsart.com" },
  { id:"n32", name:"Bloop",           slug:"bloop",           tagline:"AI code search that understands natural language queries.",                 category:"code-dev",       pricingModel:"Free",     rating:4.4, reviewCount:560,   features:["Code search","NL queries"],          platform:["Desktop"],       dateAdded:subDays(new Date(), 10).toISOString(),  logoUrl:"", websiteUrl:"https://bloop.ai" },
  { id:"n33", name:"Scholarcy",       slug:"scholarcy",       tagline:"AI research tool that summarizes academic papers instantly.",               category:"research",       pricingModel:"Freemium", rating:4.3, reviewCount:780,   features:["Paper summaries","Flashcards"],      platform:["Web"],           dateAdded:subDays(new Date(), 10).toISOString(),  logoUrl:"", websiteUrl:"https://scholarcy.com" },
  { id:"n34", name:"Tldv",            slug:"tldv",            tagline:"AI meeting recorder that transcribes and summarizes calls.",                category:"productivity",   pricingModel:"Freemium", rating:4.6, reviewCount:3400,  features:["Meeting notes","Transcription"],     platform:["Web"],           dateAdded:subDays(new Date(), 11).toISOString(),  logoUrl:"", websiteUrl:"https://tldv.io" },
  { id:"n35", name:"NightCafe",       slug:"nightcafe",       tagline:"AI art generator with multiple algorithms and styles.",                     category:"image-video",    pricingModel:"Freemium", rating:4.4, reviewCount:5600,  features:["Multiple models","Community"],       platform:["Web","Mobile"],  dateAdded:subDays(new Date(), 11).toISOString(),  logoUrl:"", websiteUrl:"https://nightcafe.studio" },
  { id:"n36", name:"Continue",        slug:"continue",        tagline:"Open-source AI code assistant for VS Code and JetBrains.",                  category:"code-dev",       pricingModel:"Free",     rating:4.5, reviewCount:1100,  features:["Open source","IDE plugin"],          platform:["Desktop"],       dateAdded:subDays(new Date(), 12).toISOString(),  logoUrl:"", websiteUrl:"https://continue.dev" },
  { id:"n37", name:"Boomy",           slug:"boomy",           tagline:"Create original songs with AI in seconds, no experience needed.",           category:"audio-music",    pricingModel:"Freemium", rating:4.1, reviewCount:3200,  features:["Song creation","Monetization"],      platform:["Web"],           dateAdded:subDays(new Date(), 12).toISOString(),  logoUrl:"", websiteUrl:"https://boomy.com" },
  { id:"n38", name:"Glasp",           slug:"glasp",           tagline:"Social web highlighter with AI-powered summaries.",                         category:"research",       pricingModel:"Free",     rating:4.4, reviewCount:890,   features:["Web highlights","AI summaries"],     platform:["Web"],           dateAdded:subDays(new Date(), 13).toISOString(),  logoUrl:"", websiteUrl:"https://glasp.co" },
  { id:"n39", name:"Simplified",      slug:"simplified",      tagline:"All-in-one design and marketing platform powered by AI.",                   category:"image-video",    pricingModel:"Freemium", rating:4.3, reviewCount:4100,  features:["Design tools","Marketing"],          platform:["Web"],           dateAdded:subDays(new Date(), 13).toISOString(),  logoUrl:"", websiteUrl:"https://simplified.com" },
  { id:"n40", name:"Raycast AI",      slug:"raycast-ai",      tagline:"AI-powered productivity launcher for Mac with ChatGPT integration.",        category:"productivity",   pricingModel:"Freemium", rating:4.8, reviewCount:2800,  features:["Mac launcher","Quick AI"],           platform:["Desktop"],       dateAdded:subDays(new Date(), 14).toISOString(),  logoUrl:"", websiteUrl:"https://raycast.com" },
];
